# ===================================================================
# The distributed file system FDFS configuration
# ===================================================================
fdfs:
  soTimeout: 15000
  connectTimeout: 3000
  maxWaitMillis: 10000
  maxIdlePerKey: 120000
  maxTotalPerKey: 200
  minEvictableIdleTimeMillis: 120000
  timeBetweenEvictionRunsMillis: 30000
  numTestsPerEvictionRun: 6
  retryAfterSecond: -1
  trackerList:            #support multiple trackers
    - 192.168.6.175:22122