INSERT INTO PUBTCOUNTRY (COUNTRY_ID,COUNTRY_NAME,ABBR_NAME,COUNTRY_DESC,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE) values
(1, 'United States', 'US', 'United States','default', now(), 'default', now());
INSERT INTO PUBTCOUNTRY (COUNTRY_ID,COUNTRY_NAME,ABBR_NAME,COUNTRY_DESC,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE) values
(2, 'Canada', 'CA', 'Canada','default', now(), 'default', now());

insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(101,1,'Alabama','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(102,1,'Alaska','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(103,1,'Arizona','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(104,1,'Arkansas','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(105,1,'California','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(106,1,'Colorado','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(107,1,'Connecticut','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(108,1,'Delaware','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(109,1,'Florida','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(110,1,'Georgia','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(111,1,'Hawaii','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(112,1,'Idaho','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(113,1,'Illinios','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(114,1,'Indiana','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(115,1,'Iowa','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(116,1,'Kansas','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(117,1,'Kentucky','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(118,1,'Louisianna','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(119,1,'Maine','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(120,1,'Maryland','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(121,1,'Massachusetts','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(122,1,'Michigan','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(123,1,'Minnesota','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(124,1,'Mississippi','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(125,1,'Missouri','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(126,1,'Montana','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(127,1,'Nebraska','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(128,1,'Nevada','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(129,1,'New Hampshire','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(130,1,'New Jersey','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(131,1,'New Mexico','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(132,1,'New York','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(133,1,'North Carolina','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(134,1,'North Dakota','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(135,1,'Ohio','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(136,1,'Oklahoma','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(137,1,'Oregon','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(138,1,'Pennsylvania','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(139,1,'Rhode Island','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(140,1,'South Carolina','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(141,1,'South Dakota','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(142,1,'Tennessee','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(143,1,'Texas','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(144,1,'Utah','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(145,1,'Vermont','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(146,1,'Virginia','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(147,1,'Washington','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(148,1,'District of Columbia','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(149,1,'West Virginia','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(150,1,'Wisconsin','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(151,1,'Wyoming','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(152,1,'American Samoa','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(153,1,'Guam','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(154,1,'Saipan(NMI)','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(155,1,'Puerto Rico','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(156,1,'US Virgin Islands','default', now(), 'default', now());

insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(157,2,'Alberta','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(158,2,'British Columbia','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(159,2,'Manitoba','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(160,2,'New Brunswick','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(161,2,'Newfoundland','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(162,2,'Northwest Territories','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(163,2,'Nova Scotia','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(164,2,'Nunavut','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(165,2,'Ontario','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(166,2,'Prince Edward Island','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(167,2,'Quebec','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(168,2,'Saskatchewan','default', now(), 'default', now());
insert into PUBTPROVINCE(PROVINCE_ID,COUNTRY_ID,PROVINCE_NAME,CREATOR,CREATE_DATE,MODIFIER,MODIFY_DATE)
values(169,2,'Yukon','default', now(), 'default', now());


commit;
